version: "2.4"

services:
  clipper:
    build:
      context: .
      target: clipper
    ports:
      - "5900:5900"
    shm_size: '1gb'
    # command: Xtigervnc :0 -geometry 1920x1080 -SecurityTypes None
    tty: true
    environment:
      - DISPLAY=:0
      - SCALE=1
    cpuset: 0-7
    mem_limit: 3g
    volumes:
      - ./shared:/shared