version: "2.4"

services:
  clipper:
    image: ghcr.io/nelsonjchen/op-replay-clipper:master
    pull_policy: always
    shm_size: '1gb'
    tty: true
    environment:
      - DISPLAY=:0
      - SCALE=1
    mem_limit: 3g
    working_dir: /workspace
    volumes:
      - ./shared:/workspace/shared
      # - ./:/workspace
  clipper_pin_090:
    # Pre-partial widecam; for stable 0.9.0
    image: ghcr.io/nelsonjchen/op-replay-clipper:pin-0.9.0
    shm_size: '1gb'
    tty: true
    environment:
      - DISPLAY=:0
      - SCALE=1
    mem_limit: 3g
    working_dir: /workspace
    volumes:
      - ./shared:/workspace/shared
      # - ./:/workspace
  dev:
    build:
      context: .
      target: clipper
    ports:
      - "5900:5900"
    shm_size: '1gb'
    tty: true
    environment:
      - DISPLAY=:0
      - SCALE=1
    # cpuset: 0-3
    mem_limit: 3g
    working_dir: /workspace
    volumes:
      - ./shared:/workspace/shared
      - ./:/workspace
